#!/usr/bin/env ruby
# Run this from inside the dotfiles dir
Dir.glob(".[a-z]*").each do |file_name|
  unless file_name == '.git'
    rm = `rm -rf ~/#{file_name}`
    ln = `ln -s ~/dotfiles/#{file_name} ~/`
  end
end
build_ct = `cd ~/.vim/ruby/command-t && ruby extconf.rb && make`
