#!/usr/bin/env ruby
Dir.glob(".[a-z]*").each do |file_name|
  unless file_name == '.git'
    rm = `rm -rf ~/#{file_name}`
    puts rm
    ln = `ln -s ~/dotfiles/#{file_name} ~/`
    puts ln
  end
end
